#!/usr/bin/env node
/**
 * Generate a local .env with strong random secrets and render runtime configs.
 * Does not overwrite existing non-default .env values unless --force is passed.
 */
import { randomBytes } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const envPath = resolve(root, '.env')
const force = process.argv.includes('--force')

const DEFAULTS = new Set([
  'password',
  'change-this-jwt-secret',
  'change-this-secret-token',
  'rustfsadmin',
  'admin',
  'replace-me',
])

const CONFIG_TARGETS = [
  {
    template: resolve(root, 'project/aitoearn-backend/apps/aitoearn-server/config/config.yaml'),
    output: resolve(root, 'project/aitoearn-backend/apps/aitoearn-server/config/config.runtime.yaml'),
  },
  {
    template: resolve(root, 'project/aitoearn-backend/apps/aitoearn-ai/config/config.yaml'),
    output: resolve(root, 'project/aitoearn-backend/apps/aitoearn-ai/config/config.runtime.yaml'),
  },
]

function randomSecret(bytes = 32) {
  return randomBytes(bytes).toString('base64url')
}

function parseEnv(content) {
  const result = {}
  for (const line of content.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#'))
      continue
    const idx = trimmed.indexOf('=')
    if (idx <= 0)
      continue
    result[trimmed.slice(0, idx)] = trimmed.slice(idx + 1)
  }
  return result
}

function needsRotate(value) {
  return !value || DEFAULTS.has(value)
}

function renderConfig(templatePath, outputPath, env) {
  let content = readFileSync(templatePath, 'utf8')
  const missing = new Set()
  content = content.replace(/%%([A-Z0-9_]+)%%/g, (_match, key) => {
    const value = env[key]
    if (value === undefined || value === '') {
      missing.add(key)
      return _match
    }
    return value
  })
  if (missing.size > 0) {
    throw new Error(`Missing secrets for ${templatePath}: ${[...missing].join(', ')}`)
  }
  mkdirSync(dirname(outputPath), { recursive: true })
  writeFileSync(outputPath, content, { mode: 0o600 })
  console.log(`Wrote ${outputPath}`)
}

const existing = existsSync(envPath) ? parseEnv(readFileSync(envPath, 'utf8')) : {}

const secrets = {
  MONGO_USERNAME: (!force && existing.MONGO_USERNAME && !needsRotate(existing.MONGO_USERNAME))
    ? existing.MONGO_USERNAME
    : 'aitoearn',
  MONGO_PASSWORD: (!force && existing.MONGO_PASSWORD && !needsRotate(existing.MONGO_PASSWORD))
    ? existing.MONGO_PASSWORD
    : randomSecret(24),
  REDIS_PASSWORD: (!force && existing.REDIS_PASSWORD && !needsRotate(existing.REDIS_PASSWORD))
    ? existing.REDIS_PASSWORD
    : randomSecret(24),
  RUSTFS_ACCESS_KEY: (!force && existing.RUSTFS_ACCESS_KEY && !needsRotate(existing.RUSTFS_ACCESS_KEY))
    ? existing.RUSTFS_ACCESS_KEY
    : randomSecret(18),
  RUSTFS_SECRET_KEY: (!force && existing.RUSTFS_SECRET_KEY && !needsRotate(existing.RUSTFS_SECRET_KEY))
    ? existing.RUSTFS_SECRET_KEY
    : randomSecret(32),
  JWT_SECRET: (!force && existing.JWT_SECRET && !needsRotate(existing.JWT_SECRET))
    ? existing.JWT_SECRET
    : randomSecret(48),
  INTERNAL_TOKEN: (!force && existing.INTERNAL_TOKEN && !needsRotate(existing.INTERNAL_TOKEN))
    ? existing.INTERNAL_TOKEN
    : randomSecret(32),
}

const content = `# Generated by scripts/bootstrap-secrets.mjs — do not commit.
# Re-run with --force to rotate all secrets (requires recreating DB/object-store volumes).

MONGO_USERNAME=${secrets.MONGO_USERNAME}
MONGO_PASSWORD=${secrets.MONGO_PASSWORD}
REDIS_PASSWORD=${secrets.REDIS_PASSWORD}
RUSTFS_ACCESS_KEY=${secrets.RUSTFS_ACCESS_KEY}
RUSTFS_SECRET_KEY=${secrets.RUSTFS_SECRET_KEY}
JWT_SECRET=${secrets.JWT_SECRET}
INTERNAL_TOKEN=${secrets.INTERNAL_TOKEN}
`

writeFileSync(envPath, content, { mode: 0o600 })
console.log(`Wrote ${envPath}`)

for (const target of CONFIG_TARGETS) {
  renderConfig(target.template, target.output, secrets)
}

console.log('Next: docker compose up -d')
console.log('If you previously started with default passwords, recreate volumes after rotating secrets.')
